/* Change this one file whenever a branch, phone number, photo, or text changes. */
const siteContent = {
  contact: { phone: "+966 54 982 0029", email: "", whatsapp: "966549820029" },
  showrooms: [
    { city: "Riyadh", name: "Al Uroubah Branch", nameAr: "فرع العروبة", address: "Al Uroubah, Riyadh, Saudi Arabia", addressAr: "العروبة، الرياض، المملكة العربية السعودية", phone: "+966 54 982 0029", hours: "Hours to be confirmed", hoursAr: "ساعات العمل قيد التأكيد", map: "https://www.google.com/maps?q=26.341014862060547,50.00664520263672&z=17&hl=en", image: "images/al-urubah.jpg" },
    { city: "Riyadh", name: "Al Shula Branch", nameAr: "فرع الشعلة", address: "Al Shula, Riyadh, Saudi Arabia", addressAr: "الشعلة، الرياض، المملكة العربية السعودية", phone: "+966 56 401 5673", hours: "Hours to be confirmed", hoursAr: "ساعات العمل قيد التأكيد", map: "https://maps.app.goo.gl/pLos61y4t92Yj9Xk6?g_st=ipc", image: "images/al-shula.jpg" },
    { city: "Riyadh", name: "Al Fursan 2 Branch", nameAr: "فرع الفرسان 2", address: "Al Fursan 2, Riyadh, Saudi Arabia", addressAr: "الفرسان 2، الرياض، المملكة العربية السعودية", phone: "+966 57 091 0668", hours: "Hours to be confirmed", hoursAr: "ساعات العمل قيد التأكيد", map: "https://maps.app.goo.gl/N9NVPutaiuuyoYcX9?g_st=iwb", image: "images/al-fursan-2.jpg" },
    { city: "Riyadh", name: "Al Fursan Branch", nameAr: "فرع الفرسان", address: "Al Fursan, Riyadh, Saudi Arabia", addressAr: "الفرسان، الرياض، المملكة العربية السعودية", phone: "+966 53 334 3501", hours: "Hours to be confirmed", hoursAr: "ساعات العمل قيد التأكيد", map: "https://share.google/Nan1KJ92CtAN4LSNA", image: "images/al-fursan.jpg" },
    { city: "Riyadh", name: "Branch 91", nameAr: "فرع 91", address: "Branch 91, Riyadh, Saudi Arabia", addressAr: "فرع 91، الرياض، المملكة العربية السعودية", phone: "+966 55 569 1266", hours: "Hours to be confirmed", hoursAr: "ساعات العمل قيد التأكيد", map: "https://goo.gl/maps/r3u747fXfMqcHxhp9", image: "images/branch-91.jpg" }
  ],
  en: { group:"BUTCHERY", navAbout:"About us", navShowrooms:"Our branches", navContact:"Contact", eyebrow:"FRESH QUALITY · EVERY DAY", heroTitle:"Exceptional meat, <em>chosen with care.</em>", heroCopy:"Fresh lamb, camel meat, poultry and more — prepared with care for every table in Riyadh.", available:"AVAILABLE TODAY", product1:"Camel meat", product2:"Lamb", product3:"Veal", explore:"Find a branch <span>↘</span>", ourStory:"Our story", branchHighlight:"Five Riyadh branches<br>tap to discover them", destinations:"five branches<br>ready to serve you", whoWeAre:"OUR STORY", introTitle:"Freshness you trust.<br><em>Service you remember.</em>", introCopy:"Jawharat Al Shami Butchery is your trusted destination for fresh quality meat in Riyadh. We select and prepare fresh lamb, camel meat, poultry and more with care, expertise and warm Arabian hospitality.", getInTouch:"Get in touch <span>→</span>", visitUs:"VISIT A BRANCH", showroomTitle:"Your nearest<br><em>Jawharat Al Shami.</em>", showroomIntro:"Five Riyadh branches. One promise of fresh quality.<br>Tap the address for directions or call the branch directly.", directions:"Directions", call:"Call branch", hours:"Opening hours", ourPromise:"OUR PROMISE", promiseTitle:"Fresh quality,<br>every time.", promise1Title:"Selected daily", promise1Copy:"Fresh meat chosen with attention to quality and care.", promise2Title:"Prepared for you", promise2Copy:"Helpful service and careful preparation for every order.", promise3Title:"Close to home", promise3Copy:"Five convenient Riyadh branches ready to welcome you.", contactUs:"CONTACT US", contactTitle:"Here to serve<br><em>your table.</em>", contactCopy:"Call or message our team for branch information and enquiries.", whatsapp:"Chat on WhatsApp <span>↗</span>", rights:"All rights reserved.", backTop:"Back to top ↑" },
  ar: { group:"للملحمة", navAbout:"من نحن", navShowrooms:"فروعنا", navContact:"تواصل معنا", eyebrow:"جودة طازجة · كل يوم", heroTitle:"لحوم مميزة، <em>مختارة بعناية.</em>", heroCopy:"لحوم ضأن وحاشي ودواجن والمزيد — نُجهزها بعناية لكل مائدة في الرياض.", available:"متوفر لدينا", product1:"حاشي", product2:"خروف", product3:"بتالو", explore:"ابحث عن فرع <span>↙</span>", ourStory:"قصتنا", branchHighlight:"خمسة فروع في الرياض<br>اضغط لاكتشافها", destinations:"خمسة فروع<br>في خدمتكم", whoWeAre:"قصتنا", introTitle:"طزاجة تثق بها.<br><em>وخدمة تتذكرها.</em>", introCopy:"ملحمة جوهرة الشامي وجهتكم الموثوقة للحوم الطازجة عالية الجودة في الرياض. نختار ونجهز لحوم الضأن والحاشي والدواجن والمزيد بعناية وخبرة وضيافة عربية أصيلة.", getInTouch:"تواصل معنا <span>←</span>", visitUs:"زوروا أحد فروعنا", showroomTitle:"أقرب فرع<br><em>لجوهرة الشامي.</em>", showroomIntro:"خمسة فروع في الرياض. وعد واحد بالجودة الطازجة.<br>اضغطوا على العنوان للاتجاهات أو اتصلوا بالفرع مباشرة.", directions:"الاتجاهات", call:"اتصل بالفرع", hours:"ساعات العمل", ourPromise:"وعدنا", promiseTitle:"جودة طازجة،<br>في كل مرة.", promise1Title:"اختيار يومي", promise1Copy:"لحوم طازجة نختارها باهتمام وعناية بالجودة.", promise2Title:"تجهيز لكم", promise2Copy:"خدمة مميزة وتجهيز دقيق لكل طلب.", promise3Title:"قريبون منكم", promise3Copy:"خمسة فروع مريحة في الرياض ترحب بكم دائماً.", contactUs:"تواصلوا معنا", contactTitle:"في خدمتكم<br><em>دائماً.</em>", contactCopy:"اتصلوا أو راسلوا فريقنا لمعلومات الفروع والاستفسارات.", whatsapp:"تحدث عبر واتساب <span>↖</span>", rights:"جميع الحقوق محفوظة.", backTop:"العودة للأعلى ↑" }
};
